### PR TITLE
Fix possible crashes when handling malformed tags

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by lazka** [comment]
hm, we'd have to see why this fails, and catch the error where it happens not two functions up.

The CI error is unrelated, I'll look into it.

**Comment by jvoisin** [comment]
Here is the stacktrace:

```python
Traceback (most recent call last):
  File "mutagen_repro.py", line 13, in <module>
    f.delete()
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/_util.py", line 160, in wrapper
    return func(self, h, *args, **kwargs)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/_file.py", line 119, in delete
    return self.tags.delete(filething)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/mp4/__init__.py", line 834, in delete
    self.save(filename, padding=lambda x: 0)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/_util.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/_util.py", line 160, in wrapper
    return func(self, h, *args, **kwargs)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/mp4/__init__.py", line 423, in save
    self.__save(filething.fileobj, atoms, data, padding)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/mp4/__init__.py", line 431, in __save
    self.__save_existing(fileobj, atoms, path, data, padding)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/mp4/__init__.py", line 497, in __save_existing
    self.__update_offsets(fileobj, atoms, delta, offset)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/mp4/__init__.py", line 548, in __update_offsets
    self.__update_offset_table(fileobj, ">%dI", atom, delta, offset)
  File "/home/jvoisin/dev/pythonfuzz/ven/lib/python3.7/site-packages/mutagen/mp4/__init__.py", line 524, in __update_offset_table
    offsets = struct.unpack(fmt, data[4:])
struct.error: unpack requires a buffer of 241680 bytes
zsh: exit 1     python mutagen_repro.py 
```

**Comment by phw** [comment]
#462 seems to be the improved version of this PR

**Comment by phw** [comment]
@jvoisin Do I see this correctly that we can close this PR since https://github.com/quodlibet/mutagen/pull/462 got merged?

**Comment by jvoisin** [comment]
Absolutely

**Pull request closed without merging**
