### PR TITLE
expose 'non-strict' apic frame changes

### PR DESCRIPTION
**Pull request by elbeardmorez**
-expose the existing 'strict' flag for loading APIC frames in the ID3Tag class
-this facilitates pushing multiple frames to a tag which happen to use the same APICType *and* description.
-by default (`strict == True`)this fails, as the sensible assumption is that the frames are the same, however, their content may differ.

### CODE REVIEW

**Comment by lazka** [comment]
Hm, what's the use case for this?

**Comment by elbeardmorez** [comment]
Hi, thanks for looking and sorry I've not fixed these failing tests yet - making time is a bit tough at the moment.

This PR was a 'necessary' placeholder for work that I'm hoping will one day make it into Quod Libet.

Specifically [this commit](https://github.com/elbeardmorez/quodlibet/commit/768397969d3a9634f59d0a5ccb9ac01cf854fb7b) requires this change.

My [widgetbar_all](https://github.com/elbeardmorez/quodlibet/commits/widgetbars_all) Quod Libet branch has 3 'widgetbars' that actually do some useful things (to hopefully go in over the [Widgetbars #2552](https://github.com/quodlibet/quodlibet/pull/2552) PR). The latter, and still currently WIP, is an 'embedded art editor'.

I have lots of files with multiple embedded art images in them. I have some for which I have multiple 'Front' and many 'Inlay/Booklet/Leaflet' art.items and plan to make more. The first of the widgetbars (Covers Widget Bar) does a decent job of displaying all the multi image (embedded or external) audio files, and has an option to display each image's name/type. I *could* load Front #2 to a different APICType ..e.g 'Other' ..or another obscure name, (eg. 14: 'During Recording') *but* that to me is a massive hack, and would result in inappropriate names being displayed in my CoversWidgetBar.plugin.

I believe the 'standard' was extremely short-sighted in its scope for this sort of thing, and hence possibly why this 'strict' flag I'm looking to expose was created in the first place.

**Comment by lazka** [comment]
1. mutagen does allow multiple APIC frames with the same type (the standard says that 1 and 2 can only be contained once, but we don't enforce that)

2. It's just some hack to load invalid files and write them back in a valid form. mutagen wont let you write invalid files even with this API change.

**Comment by elbeardmorez** [comment]
Hi,

Yes mutagen supports multiple *existing* frames which have the same APICType, but this change is trying to target *adding* of frames which have the same APICType, and hence the need to expose the (otherwise hidden) 'strict' flag to the api. Below is a snippet of the current `_add` code, see that I'm simply trying to fall through to the merge logic..

```
    def _add(self, frame, strict):
        """Add a frame.
        #....

        hash_key = frame.HashKey
        if strict or hash_key not in self:
            self[hash_key] = frame
            return
        #....

        #merge` logic
        #vvvvvvvv

```
Please see the included 'test_multi_pic' test which shows this failure to push a duplicate (and by duplicate here I explicitly mean wrt APICType ..its content matters not) without disabling this strict flag. I've just improved this test to show 'addition' replacing the existing item which is probably only desirable when image contents do match..

**Comment by lazka** [comment]
> Yes mutagen supports multiple existing frames which have the same APICType, but this change is trying to target adding of frames which have the same APICType

```python
from mutagen.id3 import ID3, APIC, PictureType

tag = ID3()
tag.add(APIC(type=PictureType.OTHER, desc="a"))
tag.add(APIC(type=PictureType.OTHER, desc="b"))

assert len(tag.getall("APIC")) == 2
```

**Comment by elbeardmorez** [comment]
Hi,

Thank you for the example, you've certainly highlighted a *large* flaw with my wording / explanation of this issue! My apologies that I haven't been precise enough thus far. The intent of this PR (pushing duplicate types) however, still remains entirely valid, I'll update the initial comment to reflect this.

```
class APIC(Frame):

    @property
    def HashKey(self):
        return '%s:%s' % (self.FrameID, self.desc)

    def _merge_frame(self, other):
        other.desc += u" "
        return other
```

With reference to the relevant parts of the APIC class above, the example you've constructed works only due to the use of a non-duplicate `desc` parameter, whereas my test code uses a (dare I say more typical) duplicate (one which duplicates `type` and `desc` ..again the content is expected to differ). The following example:

```
from mutagen.id3 import ID3, APIC, PictureType

tag = ID3()
tag.add(APIC(type=PictureType.OTHER, data=b"1"))
tag.add(APIC(type=PictureType.OTHER, data=b"2"))

assert len(tag.getall("APIC")) == 2

```
fails as I've been seeing with all my testing thus far.

So again, I'd like to be able to fall through to this (pre-existing) merge logic, and the way I see of doing that is to simply expose this 'strict' flag.

**Comment by lazka** [comment]
OK, I see.

I'm not really comfortable with exposing this as is.

For any future changes I would fear breaking existing users, as the added
frame, in case it gets merged, might change an existing one or change the
added one and the user code might not anticipate that. I don't know how to
document it besides "might change frame attributes of itself or merge with
some other frame to prevent replacing existing frames, if possible". That
seems more confusing than helpful to me.

And it's not hard to replicate what you want with the current API:
Create a frame, check if HashKey is already in the tag, if it is change one of
the attributes used in the frame key, repeat until you are happy. I can try to
add something like that to the documentation if you think that would be
helpful.

**Comment by lazka** [comment]
Added an example to the docs in 6b41a636b9997a4f0016abf9213522ff99bac55a

**Pull request closed without merging**
