### PR TITLE
Full RIFF/WAVE support with ID3 tags

### PR DESCRIPTION
**Pull request by phw**
This adds support for reading / parsing WAVE files and tagging them using ID3 tags.

This is #321 with history a little bit cleaned up and refactoring applied to address the issues discussed in #392. I opened a new PR as this is now easier to handle for me in my own fork.

The code was refactored so the RIFF code can now completely read the hierarchical RIFF chunk structure. There is explicit support for `LIST` chunks which can contain subchunks. Since the hierarchy is properly handled the code can now safely support multiple chunk insert / resize / delete operations while keeping the in-memory representation of all offsets and sizes intact. Also reading and writing the padding bytes is now all handled (previously this considered only a few special cases). You can now do things like this safely and it will all do the correct things:

```python
f = RiffFile(open('somepath'), 'rb+')
f['id3'].resize(200)
f.insert_chunk('TEST', b'some data')
f['id3'].delete()
```

The relevant changes for this are in https://github.com/quodlibet/mutagen/commit/d326665d227fd299e12c1859f32df64044faa9d5 (padding bytes fixed) and https://github.com/quodlibet/mutagen/commit/bc8e1507828cba274372e573a5baca93c2983dea (handling of the hierarchy and updating sizes / offsets after chunk changes).

Also handling of a `LIST INFO` chunk could now be easily implemented. The basic RIFF classes would support something like this to read the info:

```python
f = RiffFile(open('somepath'), 'rb+')
info = riff[u'LIST']
info_tags = {}
for chunk in info.subchunks():
    info_tags[chunk.id] = chunk.read().decode().strip('\0')
```

Or creating an info chunk:
```python
info = f.insert_chunk('LIST', b'INFO')
info.insert_chunk('IART', b'The Artist\x00')
```

The low level code is all there, so a higher level API for this could be added. But I intentionally left this out of this PR, I am not sure about a proper API for this yet. One option would be to handle this somewhat like ID3v1 is handled by having an option that automatically saves the INFO tag based on ID3 data.

@lazka @Borewit @maybeRainH I consider this now ready for review and testing, your help here is very welcomed.

Next up on my todo list is applying the refactoring here also to the AIFF code, which is plagued by the same issues of not fully handling padding bytes and damaging the files if multiple chunk changing operations are applied in one go.

### CODE REVIEW

**Comment by Borewit** [comment]
Very nice job @phw! I need to find some time to look at it in detail.

**Comment by phw** [comment]
See #409 for the corresponding AIFF changes.

**Comment by phw** [comment]
I hacked some experimental INFO chunk reading / writing into my Picard branch for WAVE support and used this to test the tagging. I added / removed / updated the ID3 chunk, the INFO chunk and individual INFO chunk elements. Did this in combination with foobar2000 and also checked the results in other tools (Windows Explorer, Totem, VLC, WMP). The data could always be read, the files kept a valid structure. I think the current state of this branch is stable.

**Comment by phw** [comment]
Rebased against current master and fixed merged conflict

**Comment by phw** [comment]
Fixed merge conflict

**Comment by Borewit** [comment]
Come on, hit that green button @lazka.

**Comment by Christilut** [comment]
Can this get merged? Would be great! :)

**Comment by phw** [comment]
@lazka Now that a new release with fixes is out, could we finally get this merged? :)

The failing tests seem to be unrelated to this PR and kind of random.

**Comment by Borewit** [comment]
This merge takes way to long (originates from Aug 17, 2017, #321), I am sorry @lazka, this is just **disrespectful** to the contributors. Significant effort has been put in this work. If you don't merge for whatever reason, then at least have the courteously to provide clarity what is causing the delay.

**Comment by phw** [comment]
I updated the branch for the latest code changes.

**Comment by Borewit** [comment]
Very nice work @phw, thank you so much for completing this.

**Pull request merged**
