### PR TITLE
allowes TYER tags in the form of 'yyyy-mm-dd'

### PR DESCRIPTION
**Pull request by lucienimmink**

### CODE REVIEW

**Comment by OxygenCobalt** [comment]
I think that violates the ID3v2 spec, TYER should only be a numeric string in the form of YYYY.

**Comment by phw** [comment]
Indeed, month and day are supposed to go into the `TDAT` frame. For a full representation including the time one would use the `TYEAR`, `TDAT`  and `TIME` frames. See https://id3.org/d3v2.3.0.

**Comment by abelcheung** [comment]
@phw bought a valid point. There are such tagged music tracks on the wild, no matter one hates it or not. In the end it comes down to where mutagen maintainers' standpoint. Do they want to handle things gracefully (like preserving data in case people want to do `update_to_v24()`), or do they have a hard stance against anything not conforming written standard? If it's the latter case, perhaps they want to make it _very_ clear, otherwise PRs like this or similar feature requests will keep coming, which is a waste of everybody's time.

**Review by phw — APPROVED** [review]
In regards of being more tolerant when reading tags and upgrading them this change looks good to me.

**Review by phw — COMMENTED** [review]
Looking at this more in context I think the upgrade probably should even use month and day if there is no `TDAT`  in the file.

Before merging we should have tests for this.

**Comment by phw** [comment]
I provided an alternative implementation in #597

**Comment by phw** [comment]
https://github.com/quodlibet/mutagen/pull/597 got merged with a bit different approach. Thanks for getting this rolling

**Pull request closed without merging**
