### PR TITLE
Fix tests on big endian architectures

### PR DESCRIPTION
**Pull request by antlarr**
I noticed these two tests were failing on BE systems
and fixes were committed to other tests with same symptoms
so I applied the same logic here to fix these.

### CODE REVIEW

**Comment by lazka** [comment]
Thanks. While it looks fine I'm wondering if we shouldn't just force a byte order/bom when writing..

**Comment by antlarr** [comment]
I'm afraid I don't know the answer to that since I'm not familiar with ID3 tags internals (just learning a bit about them lately). I just noticed these when packaging the latest version of mutagen in the openSUSE build service, which builds also ppc64 packages. In any case, if you want me to test anything on such systems, please tell me and I'll do my best to help.

**Comment by lazka** [comment]
> In any case, if you want me to test anything on such systems, please tell me and I'll do my best to help.

thanks, appreciated. I'll have a look later.

**Comment by lazka** [comment]
I've pushed a potential fix to master: c27b957e242c24b5f247a51fd1807e332fe7ef24

**Comment by antlarr** [comment]
Perfect! I tested your "potential fix" c27b957e242c24b5f247a51fd1807e332fe7ef24 on [build.opensuse.org/.../python3-mutagen](https://build.opensuse.org/package/show/home:alarrosa:branches:devel:languages:python3-tests/python3-mutagen) and it builds successfully in every architecture (tests included). At [build.opensuse.org/.../python3-mutagen/ppc64 build log](https://build.opensuse.org/package/live_build_log/home:alarrosa:branches:devel:languages:python3-tests/python3-mutagen/openSUSE_Tumbleweed/ppc64) you can see the output of the ppc64 build in case you're interested.

I'll close this pull request since it's not needed anymore.

**Comment by lazka** [comment]
Thanks for testing and packaging mutagen!

**Comment by lazka** [comment]
I'll release a 1.36.2 shortly with this fix.

**Comment by lazka** [comment]
> I'll release a 1.36.2 shortly with this fix.

done

**Comment by antlarr** [comment]
Thanks! I already submitted the new version to the openSUSE devel project at https://build.opensuse.org/request/show/452416 and it will hopefully be available in Tumbleweed soon.

**Pull request closed without merging**
