### PR TITLE
WXXX: Remove NULL-terminated character from URL

### PR DESCRIPTION
**Pull request by hlecnt**
Fix candidate for the following issue: [https://github.com/quodlibet/mutagen/issues/555](https://github.com/quodlibet/mutagen/issues/555)

### CODE REVIEW

**Comment by lazka** [comment]
hmm, according to the spec for URL frames

> If the
   text string is followed by a string termination, all the following
   information should be ignored and not be displayed.

though it's not 100% clear if that applies to WXXX

**Comment by lazka** [comment]
from what I see taglib doesn't terminate either, so maybe this is OK.

**Comment by hlecnt** [comment]
> from what I see taglib doesn't terminate either, so maybe this is OK.

I think so.

How can we go ahead with this PR ?
(I have no idea why the macos check has failed)

Regards,

**Comment by hlecnt** [comment]
Closing this PR: the issue (WXXX and TXXX frames) seems  to be specific to some MacOS + Safari versions. The current solution is to rebuild WXXX and TXXX frames by myself.

**Pull request closed without merging**
