### PR TITLE
Bug: EasyMP4 track number flow control

### PR DESCRIPTION
**Pull request by shikasta-net**
Fixing the flow control to be more robust as proposed in #413

### CODE REVIEW

**Comment by lazka** [comment]
What's the functional difference?

**Comment by shikasta-net** [comment]
It will now accept an integer.  Since the value is cast to `int` anyway, it's irrelevant that it failed to apply a string operation.

As I now understand it, the question being asked in this block is, "is this a string with a slash in it? then split and proceed else is it a string? then proceed".  I know pythoners like to work on principle of ask for forgiveness, not permission, but catching two exceptions instead of saying "is it a string?" makes it opaque: hence my not understanding that an `int` wasn't an allowed type for the tracknumber field.

**Comment by lazka** [comment]
> It will now accept an integer. Since the value is cast to `int` anyway, it's irrelevant that it failed to apply a string operation.

`"/" in 42` raises a TypeError, so I don't see how.

**Comment by lazka** [comment]
I guess this looks fine to me. I'm just confused by you using "bug" and "fixed" because I don't see it changing anything.

**Comment by shikasta-net** [comment]
OK, never mind

**Pull request closed without merging**
